### ISSUE TITLE
Value content for See and SeeAlso tags

### ISSUE THREAD

**Issue by cesarsouza** [devlooped/NuDoq#11]
Hello there,

First and foremost, thanks for creating such a useful project. I am having some trouble trying to extract the text content from <see> and <seealso> tags when they contain inner text, such as 

  `<see cref="System.Double">My own custom text here</see>`.

I am not sure if this is indeed the case, but as far as I could tell, the text between the tags was not being passed on to the Visitor class. As such, I circumvented this issue by expanding NuDoq's `See` and `SeeAlso` classes to also hold a "Content" property with the respective text. 

If this was indeed necessary, please let me know so I can submit a pull request with the changes.

Best regards,
Cesar

**Comment by kzu** [comment]
Fixed in #12
