### ISSUE TITLE
iTextSharp is not generating documentation

### ISSUE THREAD

**Issue by adamzuckerman** [devlooped/NuDoq#15]
When I try to open the iTextSharp package (using http://www.nudoq.org/#!/Errors/iTextSharp), I get the following error:

> **Generated Date:** 2/15/2014 5:17:44 AM
> 
> **Version:** 5.5.0
> 
> http://www.nuget.org/packages/iTextSharp
> 
> Error
> 
> The documentation of this package was not generated because xml documentation files could not be found in the nuget package.

When I look in the package (using NuGet Package Explorer), the XML for the DLL is in the Lib section, not in a framework specific location under Lib.  Also, the casing of the file name does not match between the DLL and the XML files.

**Comment by kzu** [comment]
The nudoq.org site has been retired a while back. This project is now about the XML doc API only.
