### ISSUE TITLE
Reading source and region attributes from Source tags

### ISSUE THREAD

**Issue by cesarsouza** [devlooped/NuDoq#18]
Hi,

In case anyone is interested, I have added support for reading "source" and "region" attributes from ```<code source="" region="">``` tags in my own fork at https://github.com/cesarsouza/NuDoq

Regards,
Cesar

**Comment by kzu** [comment]
Hey @cesarsouza, I know it's been *ages* (I'm trying to bring this a little bit up-to-date). But do you happen to recall where the definition of those two attributes comes from? I can't find any docs related to them :(.

**Comment by kzu** [comment]
Ok, I think those are coming from [sandcastle](http://ewsoftware.github.io/XMLCommentsGuide/html/1abd1992-e3d0-45b4-b43d-91fcfc5e5574.htm). Given that, once #1 is implemented, this shouldn't need a special case. I think you'd just access the extra attributes with something like `code.Attributes.TryGetValue("source", out var source)`, for example.

**Comment by cesarsouza** [comment]
Yeah, they were from Sandcastle, maybe even something specific to SHFB.

> Given that, once #1 is implemented

Just checked that, its an issue from 2013 😅 

Good luck on the update and thanks again for having built this library in the first place :-)

**Comment by kzu** [comment]
Hehe, yeah, took me a while to get back to this! 😂
