### ISSUE TITLE
Adding options to not trim new lines in text

### ISSUE THREAD

**Issue by xoofx** [devlooped/NuDoq#20]
Hi there,
Thanks for this project, it is going to save quite me some time!

While trying to use the library, I have encountered a restriction.
In the `DocReader`  method `private static string TrimText(string content)`, it will replace all new lines with a space, which is actually quite annoying for my case, as I'm writing my C# documentation using mainly markdown, so I would like to keep intact space information.

https://github.com/kzu/NuDoq/blob/1b83dae15a9e5d0cb7617068cbea225e3439f6c5/src/NuDoq/DocReader.cs#L302-L305

What do you think about having a way to pass some options to the `DocReader.Read` method to allow to control a bit more these behavior? We don't need to settle on all options.. I would just add the one that I'm interested and we could add more after.

Would you accept a PR for that? (I would transform internally the DocReader to a non static class, keeping the static methods for Read, but using instance methods internally with the options, to allow to pass through some options, it would not bring much trouble to the existing code)

**Comment by xoofx** [comment]
ah... not sure the project is still active actually...

**Comment by xoofx** [comment]
FYI, I have done something in the lines of this [commit](https://github.com/xoofx/NuDoq/commit/3531a8f677b20d43f76d5d623d408835e91cd340)

**Comment by kzu** [comment]
yeah, didn't set up CI up-front, so need to do that so merging PRs results in new packages :(

The commit looks 👍

**Comment by kzu** [comment]
Heya @xoofx, I revived this project after noticing Scriban has a copy of the dll in the repo :). So maybe you can give it a try and if it all works as expected (all issues fixed now!), maybe you can switch to the package again? I just pushed 2.0.0-beta, hoping to make it stable once it cools down for a few days.

**Comment by xoofx** [comment]
Oops, sorry, missed this notification. Some just did a PR with the package update [here](https://github.com/scriban/scriban/pull/410). Gonna give it a try. Thanks!
