### ISSUE TITLE
Don't know where to start

### ISSUE THREAD

**Issue by gordon-matt** [devlooped/NuDoq#21]
Could you please provide a more thorough example in your README? What's missing is how to use that Visitor class. After installing the NuGet package and looking at what's available via intellisense, I can guess I need to use a `DocReader` and so I have started with the following:

```
var reader = DocReader.Read(@"D:\Test\mscorlib.xml");
```

The problem now is there are only 2 properties on this class: `Elements` and `Xml`, neither of which I can figure out how to use to get the example `MarkdownVisitor` working.

I guess the solution may be obvious to some, but I am just scratching my head here. Some help would be really appreciated. Thanks!

**Comment by gordon-matt** [comment]
Ignore - I should have looked up the visitor pattern first.

**Comment by kzu** [comment]
The lack of documentation in the readme is real though. Fixing it now :)
