### ISSUE TITLE
How to get namespace info

### ISSUE THREAD

**Issue by JoshClose** [devlooped/NuDoq#40]
Is there a way to get namespace information? There isn't a visit for it.

I'm trying to generate API documentation like MS has https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.antiforgery?view=aspnetcore-5.0

**Comment by kzu** [comment]
I'm pretty sure the XML doc doesn't have an entry for namespace. That said, perhaps the visitor could keep track of the namespace of each type and the first time it sees a given namespace, call a Visit for it. Not sure what data it can provide for the method though...

**Comment by kzu** [comment]
I'm pretty sure the XML doc doesn't have an entry for namespace. That said, perhaps the visitor could keep track of the namespace of each type and the first time it sees a given namespace, call a Visit for it. Not sure what data it can provide for the method though...

**Comment by JoshClose** [comment]
If you give `DocReader.Read` an `Assembly`, it would be nice if more information was included. I'd like to create documentation similar to this https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr?view=aspnetcore-5.0.

**Comment by kzu** [comment]
Fair enough. I'd gladly take a PR that add this to the visitable hierarchy shown in the readme:

**Comment by JoshClose** [comment]
Yeah, I suppose. It was more for convenience I guess. 

I'm using Statiq and they're going to have an API generator out soon, so I'm abandoning creating my own using NuDoq. This is a really cool library though.

**Comment by kzu** [comment]
I've used docfx a few times too, and it works great for that also, i.e. dotnetconfig.org

**Comment by kzu** [comment]
Would you mind closing the issue then too? :+1:
